// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyArhIOvbOUsc6tzTr95a1-qYkJfVDlfMSg',
    appId: '1:226755567393:web:2fae05b2cce926d58ce860',
    messagingSenderId: '226755567393',
    projectId: 'app-monitorsuhu',
    authDomain: 'app-monitorsuhu.firebaseapp.com',
    databaseURL: 'https://app-monitorsuhu-default-rtdb.firebaseio.com',
    storageBucket: 'app-monitorsuhu.appspot.com',
    measurementId: 'G-C9LBZQQNW0',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBat51UEBPBuyfIsfJiPrNSBKb-um5X384',
    appId: '1:226755567393:android:2eef8dcd8191bc938ce860',
    messagingSenderId: '226755567393',
    projectId: 'app-monitorsuhu',
    databaseURL: 'https://app-monitorsuhu-default-rtdb.firebaseio.com',
    storageBucket: 'app-monitorsuhu.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChJYaBXrGl0qhr3CBKYPQgResbJz8hhos',
    appId: '1:226755567393:ios:44b02f2b9ebfe75e8ce860',
    messagingSenderId: '226755567393',
    projectId: 'app-monitorsuhu',
    databaseURL: 'https://app-monitorsuhu-default-rtdb.firebaseio.com',
    storageBucket: 'app-monitorsuhu.appspot.com',
    iosBundleId: 'com.example.appMonitorsuhu',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyChJYaBXrGl0qhr3CBKYPQgResbJz8hhos',
    appId: '1:226755567393:ios:a6d912956abad78b8ce860',
    messagingSenderId: '226755567393',
    projectId: 'app-monitorsuhu',
    databaseURL: 'https://app-monitorsuhu-default-rtdb.firebaseio.com',
    storageBucket: 'app-monitorsuhu.appspot.com',
    iosBundleId: 'com.example.appMonitorsuhu.RunnerTests',
  );
}
